# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
sitename: 탄핵 60일
# The config's title automatically shows up in the index.html, - due to lack of dev skills - I deleted it to show the title at the top of the page.
# however, I stll need to add meta data, I created new global variable, if you know how to solve this problem, Please let me know. Thanks.
email: wonkeun6@gmail.com
description: >
  박근혜 전 대통령의 탄핵 이후 60일을 기록합니다.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
paginate:	60 # The number of posts to show per page on your homepage

name: 'WangKi'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username:
facebook_username:
github_username:  wangki

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

#fill in disqus shortname to use disqus
disqus: parkoutkorea

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
